# Generated by Django 2.1.5 on 2019-10-01 13:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='images/profile_default', upload_to=users.models.upload_location),
        ),
    ]
