# Generated by Django 2.1.5 on 2019-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_homework_publisher_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
