# Generated by Django 3.0.2 on 2020-02-11 16:16

from django.db import migrations, models
import homeworks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_auto_20200211_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homeworks.utils.upload_book),
        ),
    ]
