# Generated by Django 3.0.2 on 2020-02-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0011_auto_20200211_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='full_name',
            field=models.CharField(max_length=35),
        ),
    ]
