# Generated by Django 3.0.2 on 2020-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0012_auto_20200211_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_list',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='homework',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
