# Generated by Django 3.0.2 on 2020-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0016_auto_20200217_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='summary',
            field=models.CharField(max_length=25),
        ),
    ]
