# Generated by Django 3.0.2 on 2020-02-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0017_auto_20200217_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='summary',
            field=models.CharField(max_length=40),
        ),
    ]
