# Generated by Django 3.0.2 on 2020-03-21 06:07

from django.db import migrations, models
import homeworks.utils
import homeworks.validators


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0020_auto_20200321_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homeworks.utils.upload_location, validators=[homeworks.validators.validate_image]),
        ),
    ]
