# Generated by Django 3.0.2 on 2020-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0021_auto_20200321_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_list',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
