# Generated by Django 2.1.5 on 2019-10-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeworks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[['algebra10profile2', 'Algebra 10 class profile part 2']], max_length=30)),
                ('paragraph', models.IntegerField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=homeworks.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
