# Generated by Django 2.1.5 on 2019-09-25 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='publisher',
        ),
        migrations.AddField(
            model_name='homework',
            name='publisher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
