# Generated by Django 2.1.5 on 2019-10-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('homeworks', '0002_auto_20191014_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='publisher_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
