# Generated by Django 2.1.5 on 2019-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_auto_20191014_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homework',
            name='paragraph',
            field=models.IntegerField(default=0),
        ),
    ]
