# Generated by Django 2.1.5 on 2019-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_auto_20190929_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='book',
            field=models.CharField(choices=[['algebra10profile2', 'Algebra 10 class profile part 2']], max_length=30),
        ),
    ]
