# Generated by Django 2.1.5 on 2019-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_auto_20191027_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.CharField(default='algebra', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='book',
            field=models.CharField(default='NoBook', max_length=30),
        ),
    ]
