# Generated by Django 2.1.5 on 2019-10-28 10:43

from django.db import migrations, models
import django.db.models.deletion
import homeworks.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_auto_20191027_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homeworks.models.upload_location)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='homework',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='width_field',
        ),
        migrations.AddField(
            model_name='homeworkimage',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homeworks.Homework'),
        ),
    ]
